version: "3.7"

services:

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - 5433:5432
    volumes:
      - ./postgres/volume/:/var/lib/postgresql/data
